export const mockListings = [
  {
    id: 'l-101',
    title: 'Calculus Early Transcendentals (8th Ed.)',
    description: 'Clean copy, minimal notes. Great for MATH 101 and MATH 102.',
    price: 42,
    campus: 'North Campus',
    category: 'Books',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-1',
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-1',
      name: 'Ariana Wells',
      rating: 4.8,
      transactions: 31,
    },
    postedAt: '2026-02-12T12:00:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-102',
    title: 'Dell 24" Monitor',
    description: 'Brand new in box, unused. HDMI cable included.',
    price: 140,
    campus: 'North Campus',
    category: 'Electronics',
    condition: 'New',
    type: 'NEW',
    status: 'AVAILABLE',
    sellerId: 'u-2',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-2',
      name: 'Evan Brooks',
      rating: 4.6,
      transactions: 17,
    },
    postedAt: '2026-02-15T09:20:00.000Z',
    isWishlisted: true,
  },
  {
    id: 'l-103',
    title: 'Dorm Mini Fridge',
    description: 'Used for one semester. Runs quietly.',
    price: 90,
    campus: 'Engineering Campus',
    category: 'Furniture',
    condition: 'Like New',
    type: 'SECOND_HAND',
    status: 'RESERVED',
    sellerId: 'u-3',
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1616628188859-7a11abb6fcc9?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-3',
      name: 'Nina Carter',
      rating: 4.9,
      transactions: 55,
    },
    postedAt: '2026-02-18T14:45:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-104',
    title: 'Campus Hoodie - Medium',
    description: 'Official hoodie, no damage.',
    price: 22,
    campus: 'Business Campus',
    category: 'Fashion',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'SOLD',
    sellerId: 'u-4',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-4',
      name: 'Leo Kim',
      rating: 4.4,
      transactions: 12,
    },
    postedAt: '2026-02-19T08:10:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-105',
    title: 'Programming Help Session (1 hour)',
    description: 'One-on-one tutoring for JS and React basics.',
    price: 30,
    campus: 'South Campus',
    category: 'Services',
    condition: 'New',
    type: 'NEW',
    status: 'AVAILABLE',
    sellerId: 'u-me',
    images: [
      'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-me',
      name: 'Jordan Miller',
      rating: 4.8,
      transactions: 7,
    },
    postedAt: '2026-02-20T11:35:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-106',
    title: 'TI-84 Plus CE Graphing Calculator',
    description: 'Works perfectly. Includes charging cable and cover.',
    price: 78,
    campus: 'North Campus',
    category: 'Electronics',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-5',
    images: [
      'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-5',
      name: 'Priya Singh',
      rating: 4.7,
      transactions: 23,
    },
    postedAt: '2026-02-21T12:30:00.000Z',
    isWishlisted: true,
  },
  {
    id: 'l-107',
    title: 'MacBook Air M1 (2020, 8GB/256GB)',
    description: 'Battery health 93%. Light scratches on lid, runs great.',
    price: 690,
    campus: 'Engineering Campus',
    category: 'Electronics',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-7',
    images: [
      'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-7',
      name: 'Chloe Park',
      rating: 4.9,
      transactions: 41,
    },
    postedAt: '2026-02-21T14:05:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-108',
    title: 'Desk Lamp with USB Ports',
    description: 'New in box, warm and cool light modes.',
    price: 24,
    campus: 'South Campus',
    category: 'Furniture',
    condition: 'New',
    type: 'NEW',
    status: 'AVAILABLE',
    sellerId: 'u-6',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-6',
      name: 'Mateo Cruz',
      rating: 4.5,
      transactions: 14,
    },
    postedAt: '2026-02-22T08:20:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-109',
    title: 'Road Bike Helmet (M)',
    description: 'Used for one season, no cracks, very clean.',
    price: 36,
    campus: 'South Campus',
    category: 'Sports',
    condition: 'Like New',
    type: 'SECOND_HAND',
    status: 'RESERVED',
    sellerId: 'u-9',
    images: [
      'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-9',
      name: 'Fatima Noor',
      rating: 4.8,
      transactions: 29,
    },
    postedAt: '2026-02-22T10:42:00.000Z',
    isWishlisted: true,
  },
  {
    id: 'l-110',
    title: 'Organic Chemistry Lab Coat (Medium)',
    description: 'Washed and sanitized. Fits M/L. No stains.',
    price: 18,
    campus: 'North Campus',
    category: 'Fashion',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-8',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-8',
      name: 'Daniel Ruiz',
      rating: 4.3,
      transactions: 9,
    },
    postedAt: '2026-02-22T12:00:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-111',
    title: 'Guitar Lessons (45 min)',
    description: 'Beginner to intermediate acoustic sessions.',
    price: 28,
    campus: 'Business Campus',
    category: 'Services',
    condition: 'New',
    type: 'NEW',
    status: 'AVAILABLE',
    sellerId: 'u-10',
    images: [
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-10',
      name: 'Omar Blake',
      rating: 4.6,
      transactions: 19,
    },
    postedAt: '2026-02-22T14:25:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-112',
    title: 'Ergonomic Office Chair',
    description: 'Mesh back support. Recently replaced wheels.',
    price: 85,
    campus: 'Engineering Campus',
    category: 'Furniture',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'SOLD',
    sellerId: 'u-3',
    images: [
      'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-3',
      name: 'Nina Carter',
      rating: 4.9,
      transactions: 55,
    },
    postedAt: '2026-02-22T16:10:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-113',
    title: 'Logitech MX Anywhere Mouse',
    description: 'Brand new sealed. Bluetooth + USB receiver.',
    price: 44,
    campus: 'North Campus',
    category: 'Electronics',
    condition: 'New',
    type: 'NEW',
    status: 'AVAILABLE',
    sellerId: 'u-6',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-6',
      name: 'Mateo Cruz',
      rating: 4.5,
      transactions: 14,
    },
    postedAt: '2026-02-22T17:18:00.000Z',
    isWishlisted: true,
  },
  {
    id: 'l-114',
    title: 'Intro to Economics Textbook',
    description: 'Highlighting in first 3 chapters only.',
    price: 34,
    campus: 'Business Campus',
    category: 'Books',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-10',
    images: [
      'https://images.unsplash.com/photo-1455885666463-9a08f66f8591?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-10',
      name: 'Omar Blake',
      rating: 4.6,
      transactions: 19,
    },
    postedAt: '2026-02-22T18:05:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-115',
    title: 'Soccer Cleats Size 10',
    description: 'Firm ground studs, used in 6 matches.',
    price: 40,
    campus: 'South Campus',
    category: 'Sports',
    condition: 'Good',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-9',
    images: [
      'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-9',
      name: 'Fatima Noor',
      rating: 4.8,
      transactions: 29,
    },
    postedAt: '2026-02-22T18:55:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-116',
    title: 'Frontend Portfolio Review Session',
    description: '60-minute session for CV + portfolio feedback.',
    price: 35,
    campus: 'North Campus',
    category: 'Services',
    condition: 'New',
    type: 'NEW',
    status: 'AVAILABLE',
    sellerId: 'u-me',
    images: [
      'https://images.unsplash.com/photo-1516321165247-4aa89a48be28?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-me',
      name: 'Jordan Miller',
      rating: 4.8,
      transactions: 11,
    },
    postedAt: '2026-02-22T19:45:00.000Z',
    isWishlisted: false,
  },
  {
    id: 'l-117',
    title: 'Data Structures Notes Bundle',
    description: 'Sorted notes for arrays, trees, graphs, and DP.',
    price: 16,
    campus: 'North Campus',
    category: 'Books',
    condition: 'Like New',
    type: 'SECOND_HAND',
    status: 'AVAILABLE',
    sellerId: 'u-me',
    images: [
      'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80',
    ],
    seller: {
      id: 'u-me',
      name: 'Jordan Miller',
      rating: 4.8,
      transactions: 11,
    },
    postedAt: '2026-02-22T20:20:00.000Z',
    isWishlisted: false,
  },
]

export const mockConversations = [
  {
    id: 'c-11',
    participantId: 'u-1',
    name: 'Ariana Wells',
    unread: 2,
    lastMessage: 'Can we meet at the library entrance?',
    updatedAt: '2026-02-21T09:10:00.000Z',
  },
  {
    id: 'c-12',
    participantId: 'u-3',
    name: 'Nina Carter',
    unread: 0,
    lastMessage: 'Offer accepted. Pickup tomorrow.',
    updatedAt: '2026-02-20T21:00:00.000Z',
  },
  {
    id: 'c-13',
    participantId: 'u-me',
    name: 'Jordan Miller',
    unread: 0,
    lastMessage: 'Saved draft',
    updatedAt: '2026-02-19T10:00:00.000Z',
  },
  {
    id: 'c-14',
    participantId: 'u-2',
    name: 'Evan Brooks',
    unread: 1,
    lastMessage: 'I can do 6 PM pickup near the student center.',
    updatedAt: '2026-02-22T11:14:00.000Z',
  },
  {
    id: 'c-15',
    participantId: 'u-5',
    name: 'Priya Singh',
    unread: 0,
    lastMessage: 'Calculator still available, yes.',
    updatedAt: '2026-02-22T09:42:00.000Z',
  },
  {
    id: 'c-16',
    participantId: 'u-6',
    name: 'Mateo Cruz',
    unread: 3,
    lastMessage: 'Mouse is sealed. Want photos?',
    updatedAt: '2026-02-22T21:04:00.000Z',
  },
  {
    id: 'c-17',
    participantId: 'u-9',
    name: 'Fatima Noor',
    unread: 0,
    lastMessage: 'Cleats can be tried before buying.',
    updatedAt: '2026-02-22T18:17:00.000Z',
  },
  {
    id: 'c-18',
    participantId: 'u-10',
    name: 'Omar Blake',
    unread: 0,
    lastMessage: 'Economics book can be picked up tomorrow.',
    updatedAt: '2026-02-22T17:35:00.000Z',
  },
  {
    id: 'c-19',
    participantId: 'u-7',
    name: 'Chloe Park',
    unread: 2,
    lastMessage: 'MacBook battery report uploaded.',
    updatedAt: '2026-02-22T20:52:00.000Z',
  },
]

export const mockMessages = {
  'c-11': [
    {
      id: 'm-1',
      fromMe: false,
      message: 'Hi! Is the calculus book still available?',
      createdAt: '2026-02-21T08:45:00.000Z',
    },
    {
      id: 'm-2',
      fromMe: true,
      message: 'No, it is not available.',
      createdAt: '2026-02-21T08:47:00.000Z',
    },
    {
      id: 'm-3',
      fromMe: false,
      message: 'Can we meet at the library entrance?',
      createdAt: '2026-02-21T09:10:00.000Z',
    },
  ],
  'c-12': [
    {
      id: 'm-4',
      fromMe: false,
      message: 'Offer accepted. Pickup tomorrow.',
      createdAt: '2026-02-20T21:00:00.000Z',
    },
  ],
  'c-14': [
    {
      id: 'm-5',
      fromMe: true,
      message: 'Is the monitor still under warranty?',
      createdAt: '2026-02-22T10:58:00.000Z',
    },
    {
      id: 'm-6',
      fromMe: false,
      message: 'No warranty, but zero dead pixels.',
      createdAt: '2026-02-22T11:05:00.000Z',
    },
    {
      id: 'm-7',
      fromMe: false,
      message: 'I can do 6 PM pickup near the student center.',
      createdAt: '2026-02-22T11:14:00.000Z',
    },
  ],
  'c-15': [
    {
      id: 'm-8',
      fromMe: true,
      message: 'Can you hold the calculator until Friday?',
      createdAt: '2026-02-22T09:35:00.000Z',
    },
    {
      id: 'm-9',
      fromMe: false,
      message: 'Calculator still available, yes.',
      createdAt: '2026-02-22T09:42:00.000Z',
    },
  ],
  'c-16': [
    {
      id: 'm-10',
      fromMe: false,
      message: 'Mouse is sealed. Want photos?',
      createdAt: '2026-02-22T21:04:00.000Z',
    },
  ],
  'c-17': [
    {
      id: 'm-11',
      fromMe: false,
      message: 'Cleats can be tried before buying.',
      createdAt: '2026-02-22T18:17:00.000Z',
    },
  ],
  'c-18': [
    {
      id: 'm-12',
      fromMe: true,
      message: 'Interested in the economics book. Is it available tonight?',
      createdAt: '2026-02-22T17:20:00.000Z',
    },
    {
      id: 'm-13',
      fromMe: false,
      message: 'Economics book can be picked up tomorrow.',
      createdAt: '2026-02-22T17:35:00.000Z',
    },
  ],
  'c-19': [
    {
      id: 'm-14',
      fromMe: false,
      message: 'MacBook battery report uploaded.',
      createdAt: '2026-02-22T20:52:00.000Z',
    },
  ],
}

export const mockProfile = {
  id: 'u-me',
  fullName: 'Jordan Miller',
  email: 'jordan@university.edu',
  campus: 'North Campus',
  bio: 'Computer science student building cool side projects.',
  avatar: '',
  rating: 4.8,
  listingsPosted: 7,
}

export const mockTransactions = [
  {
    id: 't-1',
    listingId: 'l-102',
    buyerId: 'u-me',
    sellerId: 'u-2',
    item: 'Dell 24" Monitor',
    amount: 140,
    status: 'Completed',
    date: '2026-01-10T12:00:00.000Z',
  },
  {
    id: 't-2',
    listingId: 'l-104',
    buyerId: 'u-6',
    sellerId: 'u-me',
    item: 'Campus Hoodie - Medium',
    amount: 22,
    status: 'Completed',
    date: '2026-01-17T12:00:00.000Z',
  },
  {
    id: 't-3',
    listingId: 'l-106',
    buyerId: 'u-me',
    sellerId: 'u-5',
    item: 'TI-84 Plus CE Graphing Calculator',
    amount: 78,
    status: 'Completed',
    date: '2026-01-22T15:20:00.000Z',
  },
  {
    id: 't-4',
    listingId: 'l-109',
    buyerId: 'u-me',
    sellerId: 'u-9',
    item: 'Road Bike Helmet (M)',
    amount: 36,
    status: 'Completed',
    date: '2026-01-26T10:45:00.000Z',
  },
  {
    id: 't-5',
    listingId: 'l-105',
    buyerId: 'u-3',
    sellerId: 'u-me',
    item: 'Programming Help Session (1 hour)',
    amount: 30,
    status: 'Completed',
    date: '2026-01-28T09:30:00.000Z',
  },
  {
    id: 't-6',
    listingId: 'l-114',
    buyerId: 'u-me',
    sellerId: 'u-10',
    item: 'Intro to Economics Textbook',
    amount: 34,
    status: 'Completed',
    date: '2026-02-02T13:05:00.000Z',
  },
  {
    id: 't-7',
    listingId: 'l-116',
    buyerId: 'u-8',
    sellerId: 'u-me',
    item: 'Frontend Portfolio Review Session',
    amount: 35,
    status: 'Completed',
    date: '2026-02-04T16:15:00.000Z',
  },
  {
    id: 't-8',
    listingId: 'l-113',
    buyerId: 'u-me',
    sellerId: 'u-6',
    item: 'Logitech MX Anywhere Mouse',
    amount: 44,
    status: 'Completed',
    date: '2026-02-08T11:50:00.000Z',
  },
  {
    id: 't-9',
    listingId: 'l-117',
    buyerId: 'u-4',
    sellerId: 'u-me',
    item: 'Data Structures Notes Bundle',
    amount: 16,
    status: 'Completed',
    date: '2026-02-11T19:10:00.000Z',
  },
]

export const mockReports = [
  {
    id: 'r-1',
    listingTitle: 'Gaming Chair - Like New',
    reason: 'Spam or scam',
    reportedBy: 'student1@university.edu',
    createdAt: '2026-02-18T15:00:00.000Z',
    status: 'Open',
  },
  {
    id: 'r-2',
    listingTitle: 'AirPods Pro (new)',
    reason: 'Counterfeit item',
    reportedBy: 'student2@university.edu',
    createdAt: '2026-02-19T10:00:00.000Z',
    status: 'Investigating',
  },
  {
    id: 'r-3',
    listingTitle: 'MacBook Air M1 (2020, 8GB/256GB)',
    reason: 'Wrong category',
    reportedBy: 'student3@university.edu',
    createdAt: '2026-02-20T13:15:00.000Z',
    status: 'Open',
  },
  {
    id: 'r-4',
    listingTitle: 'Guitar Lessons (45 min)',
    reason: 'Spam or scam',
    reportedBy: 'student4@university.edu',
    createdAt: '2026-02-21T17:40:00.000Z',
    status: 'Investigating',
  },
  {
    id: 'r-5',
    listingTitle: 'Soccer Cleats Size 10',
    reason: 'Inappropriate content',
    reportedBy: 'student5@university.edu',
    createdAt: '2026-02-22T09:55:00.000Z',
    status: 'Open',
  },
  {
    id: 'r-6',
    listingTitle: 'TI-84 Plus CE Graphing Calculator',
    reason: 'Counterfeit item',
    reportedBy: 'student6@university.edu',
    createdAt: '2026-02-22T15:05:00.000Z',
    status: 'Open',
  },
]

export const mockAdminUsers = [
  {
    id: 'a-1',
    name: 'Ariana Wells',
    email: 'ariana@university.edu',
    status: 'Active',
  },
  {
    id: 'a-2',
    name: 'Leo Kim',
    email: 'leo@university.edu',
    status: 'Suspended',
  },
  {
    id: 'a-3',
    name: 'Priya Singh',
    email: 'priya@university.edu',
    status: 'Active',
  },
  {
    id: 'a-4',
    name: 'Mateo Cruz',
    email: 'mateo@university.edu',
    status: 'Active',
  },
  {
    id: 'a-5',
    name: 'Chloe Park',
    email: 'chloe@university.edu',
    status: 'Active',
  },
  {
    id: 'a-6',
    name: 'Daniel Ruiz',
    email: 'daniel@university.edu',
    status: 'Active',
  },
  {
    id: 'a-7',
    name: 'Fatima Noor',
    email: 'fatima@university.edu',
    status: 'Suspended',
  },
  {
    id: 'a-8',
    name: 'Omar Blake',
    email: 'omar@university.edu',
    status: 'Active',
  },
]

export const mockNotifications = [
  {
    id: 'n-1',
    title: 'New message',
    body: 'Ariana sent you a message about your listing.',
    isRead: false,
    createdAt: '2026-02-21T09:11:00.000Z',
  },
  {
    id: 'n-2',
    title: 'Order completed',
    body: 'Your order for Dell 24" Monitor was completed.',
    isRead: true,
    createdAt: '2026-02-20T14:22:00.000Z',
  },
  {
    id: 'n-3',
    title: 'Listing saved',
    body: 'You saved TI-84 Plus CE Graphing Calculator.',
    isRead: false,
    createdAt: '2026-02-22T12:31:00.000Z',
  },
  {
    id: 'n-4',
    title: 'Offer update',
    body: 'Nina responded to your offer on Dorm Mini Fridge.',
    isRead: false,
    createdAt: '2026-02-22T12:56:00.000Z',
  },
  {
    id: 'n-5',
    title: 'Listing reported',
    body: 'A report was filed for one of your listings.',
    isRead: true,
    createdAt: '2026-02-22T13:42:00.000Z',
  },
  {
    id: 'n-6',
    title: 'New follower',
    body: 'A student started following your profile.',
    isRead: false,
    createdAt: '2026-02-22T16:02:00.000Z',
  },
  {
    id: 'n-7',
    title: 'Order completed',
    body: 'Your order for Intro to Economics Textbook was completed.',
    isRead: true,
    createdAt: '2026-02-22T18:43:00.000Z',
  },
  {
    id: 'n-8',
    title: 'New message',
    body: 'Omar sent you a message about the textbook listing.',
    isRead: false,
    createdAt: '2026-02-22T20:05:00.000Z',
  },
]
